CREATE TABLE user (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
)

CREATE TABLE quiz (
  id SERIAL PRIMARY KEY NOT NULL,
  url VARCHAR(255) NOT NULL,
  score INTEGER  NOT NULL DEFAULT 0,
  user_id INTEGER REFERENCES user(id) ON DELETE CASCADE
)
